# Placeholder for retrieval_config.yaml
embedding_model: "textembedding-gecko@003"
embedding_dimension: 768
matching_engine_index: "projects/YOUR_PROJECT/locations/us-central1/indexes/YOUR_INDEX"
corpus_bucket: "gs://your-bucket-name/corpus"