# Placeholder for retrieval_config.yaml
embedding_model: "text-embedding-005"
embedding_dimension: 768
matching_engine_index: "projects/insightmesh/locations/us-central1/indexes/YOUR_INDEX"
corpus_bucket: "gs://your-bucket-name/corpus"